### PR TITLE
Fix integer overflow issues

### LINKED ISSUE #227: [PE-D][Tester D] Error message for edit command with large index is inconsistent
Upon scaling the app up to have many applicants, unable to edit large indexes. Error is detected as invalid command type instead of "The provided index is invalid" as expected

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: juniper285/ped#5

### LINKED ISSUE #250: [PE-D][Tester C] Limit on the number entered for Remind Command
Description:
I entered a valid number (2^31) for the Remind Command but it was rejected (potentially due to integer overflow), recommend writing the range limit in the user guide.

Steps to reproduce:
1) Enter "Remind 2147483649"

Expected:
Either shows all the meetings with people that occurs within this number of days, or tell the user to enter a smaller number.

Actual:
Tells me that the command format is invalid without any details.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: chenxu20/ped#7

### PR DESCRIPTION
**Pull request by Ditzchann**
Fixes #250 
Fixes #227

### CODE REVIEW

File: src/main/java/hirehive/address/commons/util/StringUtil.java [hunk 1]
```diff
@@ -78,4 +78,22 @@ public static boolean isPositiveInteger(String s) {
...
+    /**
+     * Returns true if {@code s} represents a string or a valid integer
+     * @throws NullPointerException if {@code s} is null.
+     */
+    public static boolean isValidStringOrInteger(String s) {
+        requireNonNull(s);
+        if (s.matches("-?\\d+")) {
+            try {
+                long num = Long.parseLong(s);
+                return num >= Integer.MIN_VALUE && num <= Integer.MAX_VALUE;
```
Comment (deannapoh) [inline src/main/java/hirehive/address/commons/util/StringUtil.java:91]: I like how you edited it such that the range of valid numbers is wider!

File: src/main/java/hirehive/address/commons/util/StringUtil.java [hunk 2]
```diff
@@ -78,4 +78,22 @@ public static boolean isPositiveInteger(String s) {
             return false;
         }
     }
+
+    /**
+     * Returns true if {@code s} represents a string or a valid integer
+     * @throws NullPointerException if {@code s} is null.
+     */
+    public static boolean isValidStringOrInteger(String s) {
```
Comment (deannapoh) [inline src/main/java/hirehive/address/commons/util/StringUtil.java:86]: I like how you named the method like a boolean

File: src/main/java/hirehive/address/logic/parser/ParserUtil.java [hunk 3]
```diff
@@ -23,8 +23,10 @@
  */
 public class ParserUtil {
 
-    public static final String MESSAGE_INVALID_INDEX = "Index is not a non-zero unsigned integer.";
-    public static final String MESSAGE_INVALID_DAYS = "Number is not a positive integer.";
+    public static final String MESSAGE_INVALID_INDEX = "Input is not a non-zero unsigned integer.";
+    public static final String MESSAGE_INVALID_DAYS = "Input is not a positive integer.";
+    public static final String MESSAGE_OUT_OF_RANGE = "Number is out of integer range!\n"
+            + "(must be within -2^31 to 2^31 inclusive)";
```
Comment (deannapoh) [inline src/main/java/hirehive/address/logic/parser/ParserUtil.java:29]: Good that you specified which numbers are considered in range!

**Review by deannapoh — APPROVED** [review]
LGTM :)
