### PR TITLE
Resolve minor bugs in add command

### LINKED ISSUE #52: Resolve minor bugs in add command

### PR DESCRIPTION
**Pull request by deannapoh**
fixes #52

### CODE REVIEW

File: src/main/java/seedu/address/model/person/Phone.java [hunk 1]
```diff
@@ -11,8 +11,8 @@ public class Phone {
 
 
     public static final String MESSAGE_CONSTRAINTS =
-            "Phone numbers should only contain numbers, and it should be at least 3 digits long";
-    public static final String VALIDATION_REGEX = "\\d{3,}";
+            "Phone numbers should only contain numbers, and it should be an 8 digit number starting with 8, 9 or 6";
+    public static final String VALIDATION_REGEX = "[896]\\d{7}";
```
Comment (m0destly) [inline src/main/java/seedu/address/model/person/Phone.java:15]: Good to change to Singapore context, but do we want to allow numbers starting with 6 (not mobile numbers) as well?

File: src/test/java/seedu/address/model/person/PhoneTest.java [hunk 2]
```diff
@@ -27,23 +27,22 @@ public void isValidPhone() {
...
         assertFalse(Phone.isValidPhone("phone")); // non-numeric
         assertFalse(Phone.isValidPhone("9011p041")); // alphabets within digits
         assertFalse(Phone.isValidPhone("9312 1534")); // spaces within digits
 
         // valid phone numbers
-        assertTrue(Phone.isValidPhone("911")); // exactly 3 numbers
-        assertTrue(Phone.isValidPhone("93121534"));
-        assertTrue(Phone.isValidPhone("124293842033123")); // long phone numbers
+        assertTrue(Phone.isValidPhone("91112345")); // exactly 8 numbers
+        assertTrue(Phone.isValidPhone("91234567"));
```
Comment (m0destly) [inline src/test/java/seedu/address/model/person/PhoneTest.java:37]: Could consider testing a number starting with 6 if we want to allow numbers other than mobile numbers.

**Review by m0destly — APPROVED** [review]
If we accept potentially non-personal phone numbers, then LGTM!

File: src/main/java/seedu/address/model/person/Phone.java (hunk 1 above)
Comment (deannapoh) [reply src/main/java/seedu/address/model/person/Phone.java:15]: I was also thinking about it but the reason why I ultimately included the number 6 was because I wanted to just increase the scope! For instance, the elderly in Singapore may not use their mobile phones very often and may prefer to be contacted via their house phone. What are your thoughts on this though?

Comment (m0destly) [reply src/main/java/seedu/address/model/person/Phone.java:15]: I think the elderly are probably retired

Comment (deannapoh) [reply src/main/java/seedu/address/model/person/Phone.java:15]: Hmm truee I guess not a lot of them will be working... So shall I take it out?

Comment (m0destly) [reply src/main/java/seedu/address/model/person/Phone.java:15]: Can go ahead and merge first, if we think it's not as applicable in the future then we can change it again
