### PR TITLE
Fix bugs for Add Command from PE-D

### LINKED ISSUE #211: [PE-D][Tester E] Unable to include apostrophe (') in person's name
**Expected:**
To be able to add the name: Connor O'Brian

**Actual:**
Unable to add

**Suggestion/ Why it is problematic:**
Your UG does not mention the exclusion of apostrophe, only these symbols:
" Please do not use dashes(-), commas(,) and periods(.) in names.
  Example: Doe, John or Doe-John should be entered as Doe John  "

**Steps to reproduce:**
What I did was: edit 1 n/Connor O'Brian
But this error occurs with 'add' too.

**Screenshot:**

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: weiyanminoo/ped#1

### LINKED ISSUE #222: [PE-D][Tester E] Unable to add 2 people with the same name
**Expected:**
Able to add a Person with the same name as an existing contact, but all other fields are different

**Actual:**
Unable to add the person and returns: 'This person already exists in HireHive'

**Suggestion/ Why it is problematic:**
This is problematic as in the real world, 2 people with the same name can exist (especially since you did not specify in your UG that the full name must be given). Can perhaps check the other fields to see if there are any differences to check if these 2 are the exact same people.

**Steps to reproduce:**
My input:
add n/ Bernice Yu e/betsycrowe@example.com a/Ang Mo Kio Street 22 p/87654321 r/senior consulting analyst

**Screenshot:**
In the screenshot, you can see that the other fields (email, address, etc) of the 2 people are all different

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: weiyanminoo/ped#4

### LINKED ISSUE #226: [PE-D][Tester E] Allows adding of Duplicate person with extra spacing in name
**Expected:**
Reject the User from adding this entry

**Actual:**
Duplicate person is added

**Suggestion/ Why it is problematic:**
This is problematic as it could just be a type on the User's where he added extra spacing. All other fields are the same and the rest of the spelling of the name is the same as well, so this is clearly a duplicate. 

**Steps to reproduce:**
My input:
add n/Roy    Balakrishnan r/Cybersecurity specialist p/92624417 a/Blk 45 Aljunied Street 85, #11-31 e/royb@example.com

**Screenshot:**

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: weiyanminoo/ped#5

### LINKED ISSUE #255: [PE-D][Tester C] Name of person is not inclusive enough.
Description:
Adding a name with special characters like "-" or "@" are invalid, when these are perfectly legal names of a person.

Steps to reproduce:
1) Enter "edit 1 n/Tan Cheng Bok @ Adrian Tan"

Expected:
Name added successfully.

Actual:
Name rejected due to special character "@".

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: chenxu20/ped#8

### LINKED ISSUE #271: [PE-D][Tester D] Double spaces in name result in reduplicated contact
Names allow double spaces, so reducplicated contacts are created 

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: juniper285/ped#14

### LINKED ISSUE #273: [PE-D][Tester D] Unable to add names with hyphen
This does not consider for people with hyphens in their names, eg E-Hiet 

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: juniper285/ped#16

### PR DESCRIPTION
**Pull request by deannapoh**
fixes #273
fixes #271 
fixes #255 
fixes #226 
fixes #222 
fixes #211

### CODE REVIEW

File: src/main/java/hirehive/address/model/person/Name.java [hunk 1]
```diff
@@ -11,13 +11,14 @@
...
-            "Names should only contain alphanumeric characters and spaces, and it should not be blank";
+            "Names should only contain English letters, spaces, and the following symbols: , ( ) / . @ - '\n"
+                    + "It should not be blank or start with a symbol.";
 
     /*
      * The first character of the address must not be a whitespace,
      * otherwise " " (a blank string) becomes a valid input.
      */
-    public static final String VALIDATION_REGEX = "[\\p{Alnum}][\\p{Alnum} /]*";
+    public static final String VALIDATION_REGEX = "[A-Za-z][A-Za-z ,()/.@'-]*";
```
Comment (Ditzchann) [inline src/main/java/hirehive/address/model/person/Name.java:21]: I like how you made a new regex for the name validation!

File: src/test/java/hirehive/address/model/person/PersonTest.java [hunk 2]
```diff
@@ -29,24 +34,30 @@ public void isSamePerson() {
...
         Assertions.assertTrue(TypicalPersons.BOB.isSamePerson(editedBob));
 
-        // name has trailing spaces, all other attributes same -> returns false
+        // name has trailing spaces, all other attributes same -> returns true
         String nameWithTrailingSpaces = VALID_NAME_BOB + " ";
         editedBob = new PersonBuilder(TypicalPersons.BOB).withName(nameWithTrailingSpaces).build();
-        Assertions.assertFalse(TypicalPersons.BOB.isSamePerson(editedBob));
+        Assertions.assertTrue(TypicalPersons.BOB.isSamePerson(editedBob));
+
+        //name same, only phone different, all other attributes same -> returns false
```
Comment (Ditzchann) [inline src/test/java/hirehive/address/model/person/PersonTest.java:56]: I like that you created a new test case covering the event of the same name but different phone number!

File: src/main/java/hirehive/address/model/person/Name.java [hunk 3]
```diff
@@ -11,13 +11,14 @@
 public class Name {
 
     public static final String MESSAGE_CONSTRAINTS =
-            "Names should only contain alphanumeric characters and spaces, and it should not be blank";
+            "Names should only contain English letters, spaces, and the following symbols: , ( ) / . @ - '\n"
```
Comment (Ditzchann) [inline src/main/java/hirehive/address/model/person/Name.java:14]: Would it be better for you to split the symbols down onto another line for visual clarity?

**Review by Ditzchann — APPROVED** [review]
Other than some nits, looks good to me!
