### PR TITLE
Edit bug for 'edit' command for role parameter

### LINKED ISSUE #79: Edit bug for 'edit' command for role parameter

### PR DESCRIPTION
**Pull request by deannapoh**
fixes #79

### CODE REVIEW

File: src/test/java/hirehive/address/logic/commands/EditCommandTest.java [hunk 1]
```diff
@@ -68,6 +69,14 @@ public void execute_someFieldsSpecifiedUnfilteredList_success() {
         assertCommandSuccess(editCommand, model, expectedMessage, expectedModel);
     }
 
+    @Test
```
Comment (zeotheburrito) [inline src/test/java/hirehive/address/logic/commands/EditCommandTest.java:72]: Good that you added a test case to check whether the role works as intended! 👍

**Review by zeotheburrito — APPROVED** [review]
Looks good to me!
