### PR TITLE
Fix potential bug in Delete Command

### LINKED ISSUE #304: Fix potential bug in Delete Command
Current Delete Command allows for: `delete 3 n/John` , this deletes John from the contact list

Updated Delete Command will throw invalid command exception for `delete 3 n/John`

### PR DESCRIPTION
**Pull request by nat-ong555**
fixes #304

### CODE REVIEW

File: src/main/java/hirehive/address/logic/parser/DeleteCommandParser.java [hunk 1]
```diff
@@ -24,6 +24,14 @@ public class DeleteCommandParser implements Parser<DeleteCommand> {
     public DeleteCommand parse(String args) throws ParseException {
         requireNonNull(args);
         ArgumentMultimap argMultimap = ArgumentTokenizer.tokenize(args, PREFIX_NAME);
+        argMultimap.verifyNoDuplicatePrefixesFor(PREFIX_NAME);
+
+        boolean hasIndex = !argMultimap.getPreamble().isBlank();
```
Comment (deannapoh) [inline src/main/java/hirehive/address/logic/parser/DeleteCommandParser.java:29]: I like how your boolean variables has boolean names!

**Review by deannapoh — APPROVED** [review]
LGTM! You are so cool Nat!
