### PR TITLE
Fix [Add] bugs

### LINKED ISSUE #150: Fix [Add] bugs

### PR DESCRIPTION
**Pull request by deannapoh**
fixes #150, #140, #131, #153

### CODE REVIEW

File: src/main/java/hirehive/address/logic/commands/AddCommand.java [hunk 1]
```diff
@@ -30,13 +30,15 @@ public class AddCommand extends Command {
             + PREFIX_EMAIL + "EMAIL "
             + PREFIX_ADDRESS + "ADDRESS "
             + PREFIX_ROLE + "ROLE "
+            + "[" + PREFIX_NOTE + "NOTE] "
+            + "[" + PREFIX_DATE + "DATE]\n"
```
Comment (nat-ong555) [inline src/main/java/hirehive/address/logic/commands/AddCommand.java:34]: Nice that you have improved the formatting of the output message!

**Review by nat-ong555 — APPROVED** [review]
Everything LGTM!
